name: Build Eseguibili

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Controlla il Repository (Abilitando Git LFS)
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Forza il checkout degli oggetti LFS
      run: git lfs checkout

    - name: Configura Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Installa Dipendenze
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Esegui build_script.py
      run: python build_script.py

    - name: Prepara lo ZIP (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        Compress-Archive -Path dist/Cosmo-Edu_Lab_Windows.exe -DestinationPath CosmoEduLab-windows-latest.zip

    - name: Prepara lo ZIP (Mac)
      if: matrix.os == 'macos-latest'
      run: |
        if [ -d "dist/Cosmo-Edu_Lab_Mac.app" ]; then
          zip -r CosmoEduLab-macos-latest.zip dist/Cosmo-Edu_Lab_Mac.app
        else
          zip -j CosmoEduLab-macos-latest.zip dist/Cosmo-Edu_Lab_Mac
        fi

    - name: Prepara lo ZIP (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        zip -j CosmoEduLab-ubuntu-latest.zip dist/Cosmo-Edu_Lab_Linux

    - name: Carica l'archivio ZIP come Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CosmoEduLab-${{ matrix.os == 'windows-latest' && 'windows-latest' || matrix.os == 'macos-latest' && 'macos-latest' || 'ubuntu-latest' }}
        path: CosmoEduLab-*.zip

    - name: Aggiorna la Release v1.0
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "v1.0"
        files: CosmoEduLab-*.zip
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}