name: Compila Cosmo-Edu-Lab (Win, Mac, Linux)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


permissions:
  contents: write

jobs:
  build:
    name: Build su ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: 1. Scarica il codice dal repository
      uses: actions/checkout@v4

    - name: 2. Installa Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: 3. Installa PyInstaller e le dipendenze
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: 4. Lancia lo script di PyInstaller
      run: python build_script.py

    - name: 5. Salva i file eseguibili creati
      uses: actions/upload-artifact@v4
      with:
        name: CosmoEduLab-${{ matrix.os }}
        path: dist/*

  
  release:
    name: Pubblica la Release
    needs: build 
    runs-on: ubuntu-latest
    steps:
      - name: 1. Raccogli tutti gli eseguibili generati
        uses: actions/download-artifact@v4
        with:
          path: dist/
          merge-multiple: true 

      - name: 2. Aggiorna la Release in automatico
        uses: ncipollo/release-action@v1
        with:
          tag: "latest"
          name: "Cosmo-Edu Lab (Ultima Versione)"
          body: "Questi eseguibili vengono rigenerati automaticamente a ogni aggiornamento del codice."
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "dist/*"